"""update jobs table

Revision ID: 7f40d562fb65
Revises: 41556fc5e294
Create Date: 2026-06-27 22:14:04.347696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f40d562fb65'
down_revision: Union[str, Sequence[str], None] = '41556fc5e294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'created_at')
    # ### end Alembic commands ###
