"""create job summaries table

Revision ID: f72f52a6840b
Revises: baf6dafc9270
Create Date: 2026-06-28 12:10:52.901955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72f52a6840b'
down_revision: Union[str, Sequence[str], None] = 'baf6dafc9270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('total_spend_inr', sa.Float(), nullable=True),
    sa.Column('total_spend_usd', sa.Float(), nullable=True),
    sa.Column('top_merchants', sa.JSON(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.Column('narrative', sa.String(length=2000), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_job_summaries_id'), 'job_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_summaries_id'), table_name='job_summaries')
    op.drop_table('job_summaries')
    # ### end Alembic commands ###
